#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#
ARG BASE_PYTHON_IMAGE

FROM python:${BASE_PYTHON_IMAGE}

WORKDIR /agent

COPY . /agent

RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential procps \
    && cd /agent && make install \
