#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#

services:
  oap:
    container_name: oap
    image: d4701f37b0d8
    # Python agent supports gRPC/ HTTP/ Kafka reporting
    expose:
      - 11800 # gRPC
      - 12800 # HTTP
    networks:
      - manual
    environment:
      SW_STORAGE: postgresql
      SW_JDBC_URL: jdbc:postgresql://hct-converge-rds.c59etlb8vfff.ap-south-1.rds.amazonaws.com:5432/stackinsights
      SW_DATA_SOURCE_PASSWORD: G85hLjgMU
      SW_KAFKA_FETCHER: default
      SW_KAFKA_FETCHER_SERVERS: kafka:9092
      SW_KAFKA_FETCHER_PARTITIONS: 2
      SW_KAFKA_FETCHER_PARTITIONS_FACTOR: 1
    healthcheck:
      test: [ "CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/11800" ]
      interval: 5s
      timeout: 60s
      retries: 120
    ports:
      - "12800:12800"
      - "11800:11800"
    depends_on:
      - kafka


  ui:
    image: de6467b9608b
    container_name: ui
    depends_on:
      oap:
        condition: service_healthy
    networks:
      - manual
    ports:
      - "8080:8080"
    environment:
      SW_OAP_ADDRESS: "http://oap:12800"

  zookeeper:
    container_name: zk
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - manual
  
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    expose:
      - 9092
      - 9094
    ports:
      - 9092:9092
      - 9094:9094
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - manual
  
  
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8088:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - manual

networks:
  manual:
